name: "download"
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: target/
        continue-on-error: true
      - name: show currnet directory
        run: |-
          ls -R
      - name: show target/main.txt
        run: |-
          cat target/main.txt